# Generated by Django 4.2.17 on 2024-12-05 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_nome', models.CharField(max_length=512)),
                ('ca_foto', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_nome', models.CharField(max_length=512)),
                ('eq_foto', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Exercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_nome', models.CharField(max_length=512)),
                ('ex_descricao', models.CharField(max_length=512)),
                ('ex_intensidade', models.CharField(max_length=512)),
                ('ex_foto', models.CharField(max_length=512)),
                ('ex_video', models.CharField(max_length=512)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoKoyu_App.equipamento')),
                ('excercicios_categoria', models.ManyToManyField(to='ProjetoKoyu_App.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_nome', models.CharField(max_length=512)),
                ('ca_foto', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoTreinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_nome', models.CharField(max_length=512)),
                ('pt_foto', models.CharField(max_length=512)),
                ('descricao', models.CharField(max_length=512)),
                ('intensidade', models.CharField(max_length=512)),
                ('duracao', models.IntegerField()),
                ('equipamento', models.BooleanField()),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoKoyu_App.modalidade')),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ut_mail', models.CharField(max_length=512)),
                ('ut_nome', models.CharField(max_length=512)),
                ('ut_pass', models.CharField(max_length=512)),
                ('ut_estado', models.IntegerField()),
                ('ut_telefone', models.IntegerField()),
                ('ut_foto', models.CharField(max_length=512)),
                ('ut_tipo', models.CharField(max_length=512)),
                ('ut_nif', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='series_planostreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_series', models.IntegerField()),
                ('sr_repeticoes', models.IntegerField()),
                ('sr_tempo', models.FloatField()),
                ('exercicios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoKoyu_App.exercicios')),
                ('planotreinos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoKoyu_App.planotreinos')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hi_data', models.DateField()),
                ('planotreinos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoKoyu_App.planotreinos')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjetoKoyu_App.utilizador')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoria_planostreino',
            field=models.ManyToManyField(to='ProjetoKoyu_App.planotreinos'),
        ),
    ]
